export const tableConstructor = {
	year: {
		keyof: "year",
		label: "Year",
		active: true,
		readonly: true,
	},
	co2: {
		keyof: "co2",
		label: "CO₂ Emissions (kt)",
		active: true,
		readonly: true,
	},
	co2_per_capita: {
		keyof: "co2_per_capita",
		label: "CO₂ Emissions per Capita (t)",
		active: true,
		readonly: true,
	},
	population: {
		keyof: "population",
		label: "Population",
		active: true,
		readonly: true,
	},
	cement_co2: {
		keyof: "cement_co2",
		label: "Cement CO₂",
		active: false,
		readonly: false,
	},
	cement_co2_per_capita: {
		keyof: "cement_co2_per_capita",
		label: "Cement CO₂ per Capita",
		active: false,
		readonly: false,
	},
	co2_growth_abs: {
		keyof: "co2_growth_abs",
		label: "CO₂ Growth Absolute",
		active: false,
		readonly: false,
	},
	co2_growth_prct: {
		keyof: "co2_growth_prct",
		label: "CO₂ Growth Percentage",
		active: false,
		readonly: false,
	},
	co2_including_luc: {
		keyof: "co2_including_luc",
		label: "CO₂ Including Land Use Change",
		active: false,
		readonly: false,
	},
	co2_including_luc_growth_abs: {
		keyof: "co2_including_luc_growth_abs",
		label: "CO₂ Including LUC Growth Absolute",
		active: false,
		readonly: false,
	},
	co2_including_luc_growth_prct: {
		keyof: "co2_including_luc_growth_prct",
		label: "CO₂ Including LUC Growth Percentage",
		active: false,
		readonly: false,
	},
	co2_including_luc_per_capita: {
		keyof: "co2_including_luc_per_capita",
		label: "CO₂ Including LUC per Capita",
		active: false,
		readonly: false,
	},
	coal_co2: {
		keyof: "coal_co2",
		label: "Coal CO₂",
		active: false,
		readonly: false,
	},
	coal_co2_per_capita: {
		keyof: "coal_co2_per_capita",
		label: "Coal CO₂ per Capita",
		active: false,
		readonly: false,
	},
	cumulative_cement_co2: {
		keyof: "cumulative_cement_co2",
		label: "Cumulative Cement CO₂",
		active: false,
		readonly: false,
	},
	cumulative_co2: {
		keyof: "cumulative_co2",
		label: "Cumulative CO₂",
		active: false,
		readonly: false,
	},
	cumulative_co2_including_luc: {
		keyof: "cumulative_co2_including_luc",
		label: "Cumulative CO₂ Including LUC",
		active: false,
		readonly: false,
	},
	cumulative_coal_co2: {
		keyof: "cumulative_coal_co2",
		label: "Cumulative Coal CO₂",
		active: false,
		readonly: false,
	},
	cumulative_flaring_co2: {
		keyof: "cumulative_flaring_co2",
		label: "Cumulative Flaring CO₂",
		active: false,
		readonly: false,
	},
	cumulative_gas_co2: {
		keyof: "cumulative_gas_co2",
		label: "Cumulative Gas CO₂",
		active: false,
		readonly: false,
	},
	cumulative_luc_co2: {
		keyof: "cumulative_luc_co2",
		label: "Cumulative Land Use Change CO₂",
		active: false,
		readonly: false,
	},
	cumulative_oil_co2: {
		keyof: "cumulative_oil_co2",
		label: "Cumulative Oil CO₂",
		active: false,
		readonly: false,
	},
	flaring_co2: {
		keyof: "flaring_co2",
		label: "Flaring CO₂",
		active: false,
		readonly: false,
	},
	flaring_co2_per_capita: {
		keyof: "flaring_co2_per_capita",
		label: "Flaring CO₂ per Capita",
		active: false,
		readonly: false,
	},
	gas_co2: {
		keyof: "gas_co2",
		label: "Gas CO₂",
		active: false,
		readonly: false,
	},
	gas_co2_per_capita: {
		keyof: "gas_co2_per_capita",
		label: "Gas CO₂ per Capita",
		active: false,
		readonly: false,
	},
	ghg_excluding_lucf_per_capita: {
		keyof: "ghg_excluding_lucf_per_capita",
		label: "GHG Excluding LUC per Capita",
		active: false,
		readonly: false,
	},
	ghg_per_capita: {
		keyof: "ghg_per_capita",
		label: "GHG per Capita",
		active: false,
		readonly: false,
	},
	land_use_change_co2: {
		keyof: "land_use_change_co2",
		label: "Land Use Change CO₂",
		active: false,
		readonly: false,
	},
	land_use_change_co2_per_capita: {
		keyof: "land_use_change_co2_per_capita",
		label: "Land Use Change CO₂ per Capita",
		active: false,
		readonly: false,
	},
	methane: {
		keyof: "methane",
		label: "Methane",
		active: false,
		readonly: false,
	},
	methane_per_capita: {
		keyof: "methane_per_capita",
		label: "Methane per Capita",
		active: false,
		readonly: false,
	},
	nitrous_oxide: {
		keyof: "nitrous_oxide",
		label: "Nitrous Oxide",
		active: false,
		readonly: false,
	},
	nitrous_oxide_per_capita: {
		keyof: "nitrous_oxide_per_capita",
		label: "Nitrous Oxide per Capita",
		active: false,
		readonly: false,
	},
	oil_co2: {
		keyof: "oil_co2",
		label: "Oil CO₂",
		active: false,
		readonly: false,
	},
	oil_co2_per_capita: {
		keyof: "oil_co2_per_capita",
		label: "Oil CO₂ per Capita",
		active: false,
		readonly: false,
	},
	share_global_cement_co2: {
		keyof: "share_global_cement_co2",
		label: "Share Global Cement CO₂",
		active: false,
		readonly: false,
	},
	share_global_co2: {
		keyof: "share_global_co2",
		label: "Share Global CO₂",
		active: false,
		readonly: false,
	},
	share_global_co2_including_luc: {
		keyof: "share_global_co2_including_luc",
		label: "Share Global CO₂ Including LUC",
		active: false,
		readonly: false,
	},
	share_global_coal_co2: {
		keyof: "share_global_coal_co2",
		label: "Share Global Coal CO₂",
		active: false,
		readonly: false,
	},
	share_global_cumulative_cement_co2: {
		keyof: "share_global_cumulative_cement_co2",
		label: "Share Global Cumulative Cement CO₂",
		active: false,
		readonly: false,
	},
	share_global_cumulative_co2: {
		keyof: "share_global_cumulative_co2",
		label: "Share Global Cumulative CO₂",
		active: false,
		readonly: false,
	},
	share_global_cumulative_co2_including_luc: {
		keyof: "share_global_cumulative_co2_including_luc",
		label: "Share Global Cumulative CO₂ Including LUC",
		active: false,
		readonly: false,
	},
	share_global_cumulative_coal_co2: {
		keyof: "share_global_cumulative_coal_co2",
		label: "Share Global Cumulative Coal CO₂",
		active: false,
		readonly: false,
	},
	share_global_cumulative_flaring_co2: {
		keyof: "share_global_cumulative_flaring_co2",
		label: "Share Global Cumulative Flaring CO₂",
		active: false,
		readonly: false,
	},
	share_global_cumulative_gas_co2: {
		keyof: "share_global_cumulative_gas_co2",
		label: "Share Global Cumulative Gas CO₂",
		active: false,
		readonly: false,
	},
	share_global_cumulative_luc_co2: {
		keyof: "share_global_cumulative_luc_co2",
		label: "Share Global Cumulative LUC CO₂",
		active: false,
		readonly: false,
	},
	share_global_cumulative_oil_co2: {
		keyof: "share_global_cumulative_oil_co2",
		label: "Share Global Cumulative Oil CO₂",
		active: false,
		readonly: false,
	},
	share_global_flaring_co2: {
		keyof: "share_global_flaring_co2",
		label: "Share Global Flaring CO₂",
		active: false,
		readonly: false,
	},
	share_global_gas_co2: {
		keyof: "share_global_gas_co2",
		label: "Share Global Gas CO₂",
		active: false,
		readonly: false,
	},
	share_global_luc_co2: {
		keyof: "share_global_luc_co2",
		label: "Share Global LUC CO₂",
		active: false,
		readonly: false,
	},
	share_global_oil_co2: {
		keyof: "share_global_oil_co2",
		label: "Share Global Oil CO₂",
		active: false,
		readonly: false,
	},
	share_of_temperature_change_from_ghg: {
		keyof: "share_of_temperature_change_from_ghg",
		label: "Share of Temperature Change from GHG",
		active: false,
		readonly: false,
	},
	temperature_change_from_ch4: {
		keyof: "temperature_change_from_ch4",
		label: "Temperature Change from CH₄",
		active: false,
		readonly: false,
	},
	temperature_change_from_co2: {
		keyof: "temperature_change_from_co2",
		label: "Temperature Change from CO₂",
		active: false,
		readonly: false,
	},
	temperature_change_from_ghg: {
		keyof: "temperature_change_from_ghg",
		label: "Temperature Change from GHG",
		active: false,
		readonly: false,
	},
	temperature_change_from_n2o: {
		keyof: "temperature_change_from_n2o",
		label: "Temperature Change from N₂O",
		active: false,
		readonly: false,
	},
	total_ghg: {
		keyof: "total_ghg",
		label: "Total GHG",
		active: false,
		readonly: false,
	},
	total_ghg_excluding_lucf: {
		keyof: "total_ghg_excluding_lucf",
		label: "Total GHG Excluding LUC",
		active: false,
		readonly: false,
	},
} as const
